<?php
// Register Custom Post Type Special Offer
function create_specialoffer_cpt()
{

    $labels = array(
        'name' => _x('Special Offers', 'Post Type General Name', 'sa-learners-dashboard'),
        'singular_name' => _x('Special Offer', 'Post Type Singular Name', 'sa-learners-dashboard'),
        'menu_name' => _x('Special Offers', 'Admin Menu text', 'sa-learners-dashboard'),
        'name_admin_bar' => _x('Special Offer', 'Add New on Toolbar', 'sa-learners-dashboard'),
        'archives' => __('Special Offer Archives', 'sa-learners-dashboard'),
        'attributes' => __('Special Offer Attributes', 'sa-learners-dashboard'),
        'parent_item_colon' => __('Parent Special Offer:', 'sa-learners-dashboard'),
        'all_items' => __('All Special Offers', 'sa-learners-dashboard'),
        'add_new_item' => __('Add New Special Offer', 'sa-learners-dashboard'),
        'add_new' => __('Add New', 'sa-learners-dashboard'),
        'new_item' => __('New Special Offer', 'sa-learners-dashboard'),
        'edit_item' => __('Edit Special Offer', 'sa-learners-dashboard'),
        'update_item' => __('Update Special Offer', 'sa-learners-dashboard'),
        'view_item' => __('View Special Offer', 'sa-learners-dashboard'),
        'view_items' => __('View Special Offers', 'sa-learners-dashboard'),
        'search_items' => __('Search Special Offer', 'sa-learners-dashboard'),
        'not_found' => __('Not found', 'sa-learners-dashboard'),
        'not_found_in_trash' => __('Not found in Trash', 'sa-learners-dashboard'),
        'featured_image' => __('Featured Image', 'sa-learners-dashboard'),
        'set_featured_image' => __('Set featured image', 'sa-learners-dashboard'),
        'remove_featured_image' => __('Remove featured image', 'sa-learners-dashboard'),
        'use_featured_image' => __('Use as featured image', 'sa-learners-dashboard'),
        'insert_into_item' => __('Insert into Special Offer', 'sa-learners-dashboard'),
        'uploaded_to_this_item' => __('Uploaded to this Special Offer', 'sa-learners-dashboard'),
        'items_list' => __('Special Offers list', 'sa-learners-dashboard'),
        'items_list_navigation' => __('Special Offers list navigation', 'sa-learners-dashboard'),
        'filter_items_list' => __('Filter Special Offers list', 'sa-learners-dashboard'),
    );
    $args = array(
        'label' => __('Special Offer', 'sa-learners-dashboard'),
        'description' => __('', 'sa-learners-dashboard'),
        'labels' => $labels,
        'menu_icon' => 'dashicons-buddicons-community',
        'supports' => array('title', 'editor', 'excerpt', 'thumbnail'),
        'taxonomies' => array(),
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 5,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'hierarchical' => false,
        'exclude_from_search' => false,
        'show_in_rest' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
    );
    $messagesLabels = array(
        'name' => _x('Messages', 'Post Type General Name', 'sa-learners-dashboard'),
        'singular_name' => _x('Message ', 'Post Type Singular Name', 'sa-learners-dashboard'),
        'menu_name' => _x('Messages', 'Admin Menu text', 'sa-learners-dashboard'),
        'name_admin_bar' => _x('Message ', 'Add New on Toolbar', 'sa-learners-dashboard'),
        'archives' => __('Message  Archives', 'sa-learners-dashboard'),
        'attributes' => __('Message  Attributes', 'sa-learners-dashboard'),
        'parent_item_colon' => __('Parent Message :', 'sa-learners-dashboard'),
        'all_items' => __('All Messages', 'sa-learners-dashboard'),
        'add_new_item' => __('Add New Message ', 'sa-learners-dashboard'),
        'add_new' => __('Add New', 'sa-learners-dashboard'),
        'new_item' => __('New Message ', 'sa-learners-dashboard'),
        'edit_item' => __('Edit Message ', 'sa-learners-dashboard'),
        'update_item' => __('Update Message ', 'sa-learners-dashboard'),
        'view_item' => __('View Message ', 'sa-learners-dashboard'),
        'view_items' => __('View Messages', 'sa-learners-dashboard'),
        'search_items' => __('Search Message ', 'sa-learners-dashboard'),
        'not_found' => __('Not found', 'sa-learners-dashboard'),
        'not_found_in_trash' => __('Not found in Trash', 'sa-learners-dashboard'),
        'featured_image' => __('Featured Image', 'sa-learners-dashboard'),
        'set_featured_image' => __('Set featured image', 'sa-learners-dashboard'),
        'remove_featured_image' => __('Remove featured image', 'sa-learners-dashboard'),
        'use_featured_image' => __('Use as featured image', 'sa-learners-dashboard'),
        'insert_into_item' => __('Insert into Message ', 'sa-learners-dashboard'),
        'uploaded_to_this_item' => __('Uploaded to this Message ', 'sa-learners-dashboard'),
        'items_list' => __('Messages list', 'sa-learners-dashboard'),
        'items_list_navigation' => __('Messages list navigation', 'sa-learners-dashboard'),
        'filter_items_list' => __('Filter Messages list', 'sa-learners-dashboard'),
    );
    $messageArgs = array(
        'label' => __('Message ', 'sa-learners-dashboard'),
        'description' => __('', 'sa-learners-dashboard'),
        'labels' => $messagesLabels,
        'menu_icon' => 'dashicons-admin-comments',
        'supports' => array('title', 'editor', 'excerpt', 'thumbnail'),
        'taxonomies' => array(),
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 5,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'hierarchical' => false,
        'exclude_from_search' => false,
        'show_in_rest' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
    );
    register_post_type('message', $messageArgs);
    register_post_type('specialoffer', $args);
}
add_action('init', 'create_specialoffer_cpt', 0);
